### ISSUE TITLE
Dalas is also now onewire

### ISSUE THREAD

**Issue by arne182** [PricelessToolkit/Droplet#20]
https://github.com/PricelessToolkit/Droplet/blob/0d11170827e105a1d05addd280305fd42c0434d0/Config/ESPHome/droplet.yaml#L43

https://esphome.io/changelog/2024.6.0.html#ota-platforms

But I have not gotten it to compile by changing this

**Comment by PricelessToolkit** [comment]
Updated that too :)

The new way 

```yaml
one_wire: #https://esphome.io/components/one_wire
  - platform: gpio
    pin: GPIO25
```

```yaml

  - platform: dallas_temp
    address: 0xcd062180e9a6f228
    name: "${name} Integrated TMP"
    id: "intergratedtmp"
```
