### ISSUE TITLE
pH sensor

### ISSUE THREAD

**Issue by JohnMcLear** [PricelessToolkit/Droplet#24]
I'm using GPIO39 / Soil5 for pH

```
- platform: adc
  pin: GPIO39
  name: "pH"
  update_interval: 60s
  unit_of_measurement: pH
  # https://esphome.io/components/sensor/index.html#sensor-filters
  filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 3
    # Measured voltage -> Actual pH (buffer solution)
    - calibrate_linear:
        - 1.55 -> 7.0
        - 2.09 -> 4.0
  attenuation: auto
```

I removed all ref to ``Soil5``

Is this the cleanest way to do this?  Should there be a cleaner way?
